create releases on `v*.*.*` tags
webxdc/store pull request #129
Opened 2023-06-29 15:31 UTC by adbenitez

2023-06-29 16:49 UTC, adbenitez commented on README.md
> +git tag v1.0.1
updated, thanks!!! :+1:

2023-06-30 19:43 UTC, Septias requested changes
Can you depend on `build_dist` instead of building the tarball from scratch?

2023-07-01 18:53 UTC, adbenitez commented
> Can you depend on `build_dist` instead of building the tarball from scratch?

this was easier for me, but feel free to push improvements to this PR

2023-07-05 23:15 UTC, Septias approved these changes

2023-07-05 23:15 UTC, Septias commented
let's just merge this, I can make improvements later if it annoys me too much

2023-07-06 12:46 UTC, r10s commented
> let's just merge this, I can make improvements later if it annoys me too much

i would not put too much effort in that :)

we still still aim to this repository to codeberg, so any effort wrt ci is better done there

2023-07-06 12:55 UTC, adbenitez commented
> EDIT: /me speaking about CI only. just noticing that, other that the title implies, this pr is doing tons of other things :)

that was me trying to rebase hehe



> i would not put too much effort in that :)

at this point there is no effort other than pressing the merge button

2023-07-06 12:57 UTC, r10s commented
> at this point there is no effort other than pressing the merge button

sure, all fine. i was referring to "I can make improvements later" :)

2023-07-06 12:59 UTC, merged